[tool.poetry]
name = "pilot_log"
version = "0.1.0"
description = "Simple Django pilot log webapp"
authors = ["Yury V. Zaytsev <yury@shurup.com>"]
license = "MIT"

[tool.poetry.dependencies]
Django = "<2.3"
django-countries = "*"

python = "^3.8"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
