[tool.poetry]
name = "pilot_log"
version = "0.1.0"
description = "Simple Django pilot log webapp"
authors = ["Yury V. Zaytsev <yury@shurup.com>"]
license = "MIT"

[tool.poetry.dependencies]
django = "*"
django-countries = "*"
django-bootstrap5 = "*"

python = "^3.11"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"

flake8 = "*"
flake8-black = "*"
flake8-coding = "*"
flake8-isort = "*"
flake8-quotes = "*"

black = "*"
isort = {extras = ["pyproject"], version = "*"}
add-trailing-comma = "*"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 120

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
